name: ble_chat_flutter
packages:
  - app
  - packages/*
command:
  bootstrap:
    usePubspecOverrides: true
scripts:
  gen: dart run build_runner build --delete-conflicting-outputs
  clean: |
    melos exec -- "flutter clean"
    melos exec -- "dart pub cache repair" # 可按需移除
  format: melos exec -- "dart format ."
  test: melos exec -- "flutter test --no-pub"
  list: melos list
  get: melos exec -- "flutter pub get"
